// Sample data for demonstration
export const initialTasks = [
  {
    id: 1,
    title: "Design new landing page",
    description:
      "Create wireframes and mockups for the new marketing landing page. Include mobile and desktop versions with all necessary components.",
    status: "todo",
    priority: "high",
    assignee: "Alex Johnson",
    dueDate: "2024-06-01",
    createdAt: "2024-05-15T10:30:00",
    updatedAt: "2024-05-15T10:30:00",
    tags: ["design", "marketing"],
    comments: [
      { id: 1, user: "Sarah Kim", text: "Should we use the new brand colors?", timestamp: "2024-05-20T10:30:00" },
    ],
    attachments: [],
    activity: [
      { id: 1, type: "created", user: "Emily Rodriguez", timestamp: "2024-05-15T10:30:00" },
      { id: 2, type: "comment_added", user: "Sarah Kim", timestamp: "2024-05-20T10:30:00" },
    ],
  },
  {
    id: 2,
    title: "Implement authentication flow",
    description:
      "Set up user registration, login, and password reset functionality. Integrate with the backend API and add form validation.",
    status: "in-progress",
    priority: "high",
    assignee: "Michael Chen",
    dueDate: "2024-05-28",
    createdAt: "2024-05-10T14:20:00",
    updatedAt: "2024-05-18T09:15:00",
    tags: ["development", "security"],
    comments: [],
    attachments: [
      {
        id: 1,
        name: "auth-flow-diagram.pdf",
        size: "1.2 MB",
        type: "application/pdf",
        uploadedBy: "Emily Rodriguez",
        uploadedAt: "2024-05-10T15:30:00",
        url: "#",
      },
    ],
    activity: [
      { id: 1, type: "created", user: "Emily Rodriguez", timestamp: "2024-05-10T14:20:00" },
      {
        id: 2,
        type: "attachment_added",
        user: "Emily Rodriguez",
        details: "Added auth-flow-diagram.pdf",
        timestamp: "2024-05-10T15:30:00",
      },
      {
        id: 3,
        type: "status_changed",
        user: "Michael Chen",
        details: "Status changed to in-progress",
        timestamp: "2024-05-18T09:15:00",
      },
    ],
  },
  {
    id: 3,
    title: "Write API documentation",
    description:
      "Document all API endpoints with examples and response schemas. Include authentication requirements and error handling.",
    status: "in-progress",
    priority: "medium",
    assignee: "Emily Rodriguez",
    dueDate: "2024-05-30",
    createdAt: "2024-05-12T11:45:00",
    updatedAt: "2024-05-19T14:15:00",
    tags: ["documentation", "api"],
    comments: [
      { id: 1, user: "Michael Chen", text: "I'll review this when you're done", timestamp: "2024-05-19T14:15:00" },
    ],
    attachments: [],
    activity: [
      { id: 1, type: "created", user: "Emily Rodriguez", timestamp: "2024-05-12T11:45:00" },
      { id: 2, type: "comment_added", user: "Michael Chen", timestamp: "2024-05-19T14:15:00" },
    ],
  },
  {
    id: 4,
    title: "Fix responsive layout issues",
    description: "Address UI bugs on mobile devices. Focus on the navigation menu, product cards, and checkout flow.",
    status: "todo",
    priority: "medium",
    assignee: "Alex Johnson",
    dueDate: "2024-06-02",
    createdAt: "2024-05-17T09:30:00",
    updatedAt: "2024-05-17T09:30:00",
    tags: ["bug", "ui", "responsive"],
    comments: [],
    attachments: [],
    activity: [{ id: 1, type: "created", user: "Emily Rodriguez", timestamp: "2024-05-17T09:30:00" }],
  },
  {
    id: 5,
    title: "Set up CI/CD pipeline",
    description:
      "Configure automated testing and deployment workflow using GitHub Actions. Include linting, unit tests, and deployment to staging.",
    status: "completed",
    priority: "high",
    assignee: "Michael Chen",
    dueDate: "2024-05-15",
    createdAt: "2024-05-05T13:20:00",
    updatedAt: "2024-05-15T16:45:00",
    tags: ["devops", "automation"],
    comments: [],
    attachments: [],
    activity: [
      { id: 1, type: "created", user: "Emily Rodriguez", timestamp: "2024-05-05T13:20:00" },
      {
        id: 2,
        type: "status_changed",
        user: "Michael Chen",
        details: "Status changed to in-progress",
        timestamp: "2024-05-08T10:15:00",
      },
      {
        id: 3,
        type: "status_changed",
        user: "Michael Chen",
        details: "Status changed to completed",
        timestamp: "2024-05-15T16:45:00",
      },
    ],
  },
  {
    id: 6,
    title: "Conduct user testing",
    description:
      "Organize sessions to gather feedback on the new features. Prepare test scenarios and recruit participants.",
    status: "todo",
    priority: "low",
    assignee: "Sarah Kim",
    dueDate: "2024-06-10",
    createdAt: "2024-05-18T15:10:00",
    updatedAt: "2024-05-18T15:10:00",
    tags: ["testing", "user-research"],
    comments: [],
    attachments: [],
    activity: [{ id: 1, type: "created", user: "Emily Rodriguez", timestamp: "2024-05-18T15:10:00" }],
  },
  {
    id: 7,
    title: "Optimize database queries",
    description: "Improve performance of slow-running queries. Add indexes and refactor problematic queries.",
    status: "completed",
    priority: "medium",
    assignee: "Michael Chen",
    dueDate: "2024-05-18",
    createdAt: "2024-05-08T11:30:00",
    updatedAt: "2024-05-18T14:20:00",
    tags: ["database", "performance"],
    comments: [],
    attachments: [],
    activity: [
      { id: 1, type: "created", user: "Emily Rodriguez", timestamp: "2024-05-08T11:30:00" },
      {
        id: 2,
        type: "status_changed",
        user: "Michael Chen",
        details: "Status changed to in-progress",
        timestamp: "2024-05-10T09:45:00",
      },
      {
        id: 3,
        type: "status_changed",
        user: "Michael Chen",
        details: "Status changed to completed",
        timestamp: "2024-05-18T14:20:00",
      },
    ],
  },
  {
    id: 8,
    title: "Create onboarding tutorial",
    description:
      "Design and implement an interactive tutorial for new users. Include tooltips and guided walkthroughs of key features.",
    status: "review",
    priority: "medium",
    assignee: "Alex Johnson",
    dueDate: "2024-05-25",
    createdAt: "2024-05-10T10:15:00",
    updatedAt: "2024-05-22T11:30:00",
    tags: ["design", "onboarding", "ux"],
    comments: [
      {
        id: 1,
        user: "Emily Rodriguez",
        text: "This looks great! Just a few minor tweaks needed.",
        timestamp: "2024-05-22T11:30:00",
      },
    ],
    attachments: [],
    activity: [
      { id: 1, type: "created", user: "Emily Rodriguez", timestamp: "2024-05-10T10:15:00" },
      {
        id: 2,
        type: "status_changed",
        user: "Alex Johnson",
        details: "Status changed to in-progress",
        timestamp: "2024-05-12T09:30:00",
      },
      {
        id: 3,
        type: "status_changed",
        user: "Alex Johnson",
        details: "Status changed to review",
        timestamp: "2024-05-22T11:00:00",
      },
      { id: 4, type: "comment_added", user: "Emily Rodriguez", timestamp: "2024-05-22T11:30:00" },
    ],
  },
  {
    id: 9,
    title: "Update privacy policy",
    description:
      "Review and update the privacy policy to comply with new regulations. Consult with legal team on required changes.",
    status: "review",
    priority: "high",
    assignee: "Emily Rodriguez",
    dueDate: "2024-05-24",
    createdAt: "2024-05-15T13:45:00",
    updatedAt: "2024-05-21T16:20:00",
    tags: ["legal", "compliance"],
    comments: [],
    attachments: [
      {
        id: 1,
        name: "privacy-policy-draft.docx",
        size: "245 KB",
        type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        uploadedBy: "Emily Rodriguez",
        uploadedAt: "2024-05-21T16:20:00",
        url: "#",
      },
    ],
    activity: [
      { id: 1, type: "created", user: "Sarah Kim", timestamp: "2024-05-15T13:45:00" },
      {
        id: 2,
        type: "status_changed",
        user: "Emily Rodriguez",
        details: "Status changed to in-progress",
        timestamp: "2024-05-16T10:30:00",
      },
      {
        id: 3,
        type: "status_changed",
        user: "Emily Rodriguez",
        details: "Status changed to review",
        timestamp: "2024-05-21T16:15:00",
      },
      {
        id: 4,
        type: "attachment_added",
        user: "Emily Rodriguez",
        details: "Added privacy-policy-draft.docx",
        timestamp: "2024-05-21T16:20:00",
      },
    ],
  },
  {
    id: 10,
    title: "Implement dark mode",
    description: "Add dark mode support to the application. Create new color variables and toggle functionality.",
    status: "todo",
    priority: "low",
    assignee: "",
    dueDate: "2024-06-05",
    createdAt: "2024-05-20T09:15:00",
    updatedAt: "2024-05-20T09:15:00",
    tags: ["ui", "feature"],
    comments: [],
    attachments: [],
    activity: [{ id: 1, type: "created", user: "Alex Johnson", timestamp: "2024-05-20T09:15:00" }],
  },
]

export const initialTeamMembers = [
  {
    id: 1,
    name: "Alex Johnson",
    email: "alex@example.com",
    role: "Designer",
    permission: "editor",
    avatar: "/placeholder.svg?height=40&width=40",
    tasks: 8,
    completedTasks: 5,
  },
  {
    id: 2,
    name: "Michael Chen",
    email: "michael@example.com",
    role: "Developer",
    permission: "admin",
    avatar: "/placeholder.svg?height=40&width=40",
    tasks: 12,
    completedTasks: 9,
  },
  {
    id: 3,
    name: "Emily Rodriguez",
    email: "emily@example.com",
    role: "Product Manager",
    permission: "admin",
    avatar: "/placeholder.svg?height=40&width=40",
    tasks: 15,
    completedTasks: 10,
  },
  {
    id: 4,
    name: "Sarah Kim",
    email: "sarah@example.com",
    role: "Marketing",
    permission: "viewer",
    avatar: "/placeholder.svg?height=40&width=40",
    tasks: 6,
    completedTasks: 3,
  },
]

